camera/Controllers/CarparkprovidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using camera.DAL;

namespace camera.Controllers
{
    public class CarparkprovidersController : Controller
    {
        private tls_dbEntities db = new tls_dbEntities();

        // GET: Carparkproviders
        public ActionResult Index()
        {
            return View(db.carparkproviders.ToList());
        }

        // GET: Carparkproviders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            carparkprovider carparkprovider = db.carparkproviders.Find(id);
            if (carparkprovider == null)
            {
                return HttpNotFound();
            }
            return View(carparkprovider);
        }

        // GET: Carparkproviders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carparkproviders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CarparkProviderID,ProviderName,ActiveAccountNum")] carparkprovider carparkprovider)
        {
            if (ModelState.IsValid)
            {
                db.carparkproviders.Add(carparkprovider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(carparkprovider);
        }

        // GET: Carparkproviders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            carparkprovider carparkprovider = db.carparkproviders.Find(id);
            if (carparkprovider == null)
            {
                return HttpNotFound();
            }
            return View(carparkprovider);
        }

        // POST: Carparkproviders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CarparkProviderID,ProviderName,ActiveAccountNum")] carparkprovider carparkprovider)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carparkprovider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carparkprovider);
        }

        // GET: Carparkproviders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            carparkprovider carparkprovider = db.carparkproviders.Find(id);
            if (carparkprovider == null)
            {
                return HttpNotFound();
            }
            return View(carparkprovider);
        }

        // POST: Carparkproviders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            carparkprovider carparkprovider = db.carparkproviders.Find(id);
            db.carparkproviders.Remove(carparkprovider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

camera/Views/Shared/DetPartial.cshtml
@model IEnumerable<camera.Models.ScanResult>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

camera/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>  
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TLS Parking System", "Index", "Home", new { @class = "navbar-brand" })
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                            <li>@Html.ActionLink("Car Park", "Index", "Carparkproviders")</li>
                            <li>@Html.ActionLink("Parking","Index","Parking")</li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->  
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TLS Parking Systems</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>